# refusing to allow a GitHub App to create or update workflow .github/workflows/XXXX.yml without workflows permission
# 遇到这个错误，需要检查三点：
# 1. 仓库设置 Workflow permissions 允许写权限
# 2. 使用的 TOKEN 具有 workflows 权限，如果是组织仓库还需要检查 TOKEN 的作用域
# 3. actions/checkout 也需要使用 workflows 权限的 TOKEN
# -------------------------------------------------------------------
# https://github.com/Soltus

name: Test

on:
  workflow_call:
    inputs:
      target_sync_repo:
        description: "目标（下游）仓库，格式为 owner/repository ，必须指定"
        required: true
        type: string
      target_sync_branch:
        description: "目标（下游）同步分支，必须指定"
        required: true
        type: string
      upstream_sync_repo:
        description: "上游仓库，默认为 github.repository ，根据实际情况修改"
        type: string
        default: ${{ github.repository }}
      upstream_sync_branch:
        description: "上游同步分支，必须指定"
        required: true
        type: string
      sync_test_mode: # Adds a boolean option that appears during manual workflow run for easy test mode config
        description: 'Fork Sync Test Mode'
        type: boolean
        default: false

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
      # REQUIRED step
      # Step 1: run a standard checkout action, provided by github
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.target_sync_repo }}
          fetch-depth: 0
          token: ${{ secrets.TOEKN_FOREVER_FULL_WRITE }} # 使用具有完全写入权限的 TOKEN（必须包含 workflows ）
          # REQUIRED if your upstream repo is private (see wiki), 启用会造成 check-branch-exists 失败
          # persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Check if target_sync_branch exists in the remote
        id: check-branch-exists
        run: |
          # Use GitHub API to get the branch information
          RESPONSE=$(curl -s -H "Authorization: token${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ inputs.target_sync_repo }}/branches/${{ inputs.target_sync_branch }}")
          # Check if the response contains 'Not Found' which indicates the branch does not exist
          if echo "$RESPONSE" | grep -q "Not Found"; then
            echo "branch_exists=false" >> $GITHUB_OUTPUT
            echo "Remote branch ${{ inputs.target_sync_branch }} does not exist."
            git remote add upstream https://github.com/${{ inputs.upstream_sync_repo }}.git
            # 创建一个临时分支来fetch远程分支的内容
            git fetch upstream ${{ inputs.upstream_sync_branch }}:temp_${{ inputs.upstream_sync_branch }}
            # 基于临时分支创建新的本地分支
            git checkout -b ${{ inputs.target_sync_branch }} temp_${{ inputs.upstream_sync_branch }}
            # 删除临时分支
            git branch -d temp_${{ inputs.upstream_sync_branch }}
            # 推送新分支到远程仓库
            git push origin ${{ inputs.target_sync_branch }}
          else
            echo "branch_exists=true" >> $GITHUB_OUTPUT
            echo "Remote branch ${{ inputs.target_sync_branch }} exists."
            git checkout ${{ inputs.target_sync_branch }}
          fi

      # REQUIRED step
      # Step 2: run the sync action
      - name: Sync upstream changes
        id: sync
        if: steps.check-branch-exists.outputs.branch_exists == 'true'
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: ${{ inputs.target_sync_branch }}
          target_repo_token: ${{ secrets.TOEKN_FOREVER_FULL_WRITE }} # 可能涉及 workflows 的修改，需要对应权限
          upstream_sync_branch: ${{ inputs.upstream_sync_branch }}
          upstream_sync_repo: ${{ inputs.upstream_sync_repo }}
          test_mode: ${{ inputs.sync_test_mode }}

      # Step 3: Display a sample message based on the sync output var 'has_new_commits'
      - name: New commits found
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "New commits were found to sync."

      - name: No new commits
        if: steps.sync.outputs.has_new_commits == 'false'
        run: echo "There were no new commits."

      - name: Show value of 'has_new_commits'
        run: echo ${{ steps.sync.outputs.has_new_commits }}
