name: test all

# 这里通过手动触发器触发，也可以自定义其他触发方式
on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/validation.yml
    secrets: inherit
    with:
      cd_path: "test/ci"
      cd_branch: "main_-_cd_-_test"
      dist_path: "test/src"
      dist_branch: "main_-_dist_-_test"
  test2:
    uses: ./.github/workflows/validation.yml
    secrets: inherit
    with:
      cd_path: "test2/ci"
      cd_branch: "main_-_cd_-_test2"
      dist_path: "test2/src"
      dist_branch: "main_-_dist_-_test2"