name: test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/validation-proxy.yml
    secrets: inherit
    with:
      name: "test"
  # sync:
  #   uses: prototype-test/dist-repo-use-branch_test/.github/workflows/test.yml@main_-_cd_-_test
  #   secrets: inherit
  #   needs: build