name: test all

# 这里通过手动触发器触发，也可以自定义其他触发方式
on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  test2:
    uses: ./.github/workflows/test2.yml
    secrets: inherit