name: test all

# 这里通过手动触发器触发，也可以自定义其他触发方式
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test"
  test2:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test2"
  test3:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test3"
  test4:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test4"
  test5:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test5"
  test6:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test6"