name: test all

# 这里通过主分支的 push 和手动触发器触发，也可以自定义其他触发方式
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.config.repo }}
    name: ${{ matrix.config.repo_name }}
    strategy:
      matrix:
        config:
          - repo: test
            repo_name: test
          - repo: test2
            repo_name: test2
    steps:
      - uses: ./.github/workflows/validation.yml
        with:
          cd_path: "${{ matrix.config.repo }}/ci" # (Github）持续交付路径, 不能以 / 结尾
          cd_branch: "main_-_cd_-_${{ matrix.config.repo }}" # 不能包含 / 等字符
          dist_path: "${{ matrix.config.repo }}/src" # 分发路径, 不能以 / 结尾
          dist_branch: "main_-_dist_-_${{ matrix.config.repo }}" # 不能包含 / 等字符