name: test2

# 这里通过主分支的 push 和手动触发器触发，也可以自定义其他触发方式
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  cd_branch_prefix: ${{ github.ref }}_-_cd_-_
  dist_branch_prefix: ${{ github.ref }}_-_dist_-_
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cd_branch_prefix: ${{ env.cd_branch_prefix }}
      dist_branch_prefix: ${{ env.dist_branch_prefix }}
  build:
    needs: setup
    uses: ./.github/workflows/validation.yml
    secrets: inherit
    with:
      cd_path: "test2/ci"
      cd_branch: "${{ needs.setup.outputs.cd_branch_prefix }}test2"
      dist_path: "test2/src"
      dist_branch: "${{ needs.setup.outputs.dist_branch_prefix }}test2"