name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: "目标名，必须指定"
        type: choice
        options:
        - test1
        - test2
        - test3
        - test4
        - test5
        - test6
        - test7
        - test8
        - test9
        - test10
        - test11
        - test12
        - test13
        - test14
        - test15
        - test16
        - test17
        - test18
        - test19
        - test20
        - test21
        - test22
      repo_name:
        description: "目标（下游）仓库，格式为 owner/repository ，必须指定"
        required: true
        type: string
      upstream_dist_path:
        description: "上游仓库分发路径，必须指定，不能以 / 结尾"
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/validation-proxy.yml
    secrets: inherit
    with:
      name: ${{ inputs.name }}
      repo_name: ${{ inputs.repo_name }}
      upstream_dist_path: ${{ inputs.upstream_dist_path }}