name: test

# 这里通过主分支的 push 和手动触发器触发，也可以自定义其他触发方式
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/validation.yml
    secrets: inherit
    with:
      cd_path: "test/ci"
      cd_branch: "main_-_cd_-_test"
      dist_path: "test/src"
      dist_branch: "main_-_dist_-_test"