name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: "目标名，必须指定"
        required: true
        type: string
      repo_name:
        description: "目标（下游）仓库，格式为 owner/repository ，必须指定"
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/validation-proxy.yml
    secrets: inherit
    with:
      name: ${{ inputs.name }}
      repo_name: ${{ inputs.repo_name }}