name: test all

# 这里通过手动触发器触发，也可以自定义其他触发方式
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test1:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test1"
      repo_name: "prototype-test/dist-repo-use-branch_test1"
      upstream_dist_path: "test/test1"
  test2:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test2"
      repo_name: "prototype-test/dist-repo-use-branch_test2"
      upstream_dist_path: "test/test2"
  test3:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test3"
      repo_name: "prototype-test/dist-repo-use-branch_test3"
      upstream_dist_path: "test/test3"
  test4:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test4"
      repo_name: "prototype-test/dist-repo-use-branch_test4"
      upstream_dist_path: "test/test4"
  test5:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test5"
      repo_name: "prototype-test/dist-repo-use-branch_test5"
      upstream_dist_path: "test/test5"
  test6:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test6"
      repo_name: "prototype-test/dist-repo-use-branch_test6"
      upstream_dist_path: "test/test6"
  test7:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test7"
      repo_name: "prototype-test/dist-repo-use-branch_test7"
      upstream_dist_path: "test/test7"
  test8:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test8"
      repo_name: "prototype-test/dist-repo-use-branch_test8"
      upstream_dist_path: "test/test8"
  test9:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test9"
      repo_name: "prototype-test/dist-repo-use-branch_test9"
      upstream_dist_path: "test/test9"
  test10:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test10"
      repo_name: "prototype-test/dist-repo-use-branch_test10"
      upstream_dist_path: "test/test10"
  test11:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test11"
      repo_name: "prototype-test/dist-repo-use-branch_test11"
      upstream_dist_path: "test/test11"
  test12:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test12"
      repo_name: "prototype-test/dist-repo-use-branch_test12"
      upstream_dist_path: "test/test12"
  test13:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test13"
      repo_name: "prototype-test/dist-repo-use-branch_test13"
      upstream_dist_path: "test/test13"
  test14:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test14"
      repo_name: "prototype-test/dist-repo-use-branch_test14"
      upstream_dist_path: "test/test14"
  test15:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test15"
      repo_name: "prototype-test/dist-repo-use-branch_test15"
      upstream_dist_path: "test/test15"
  test16:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test16"
      repo_name: "prototype-test/dist-repo-use-branch_test16"
      upstream_dist_path: "test/test16"
  test17:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test17"
      repo_name: "prototype-test/dist-repo-use-branch_test17"
      upstream_dist_path: "test/test17"
  test18:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test18"
      repo_name: "prototype-test/dist-repo-use-branch_test18"
      upstream_dist_path: "test/test18"
  test19:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test19"
      repo_name: "prototype-test/dist-repo-use-branch_test19"
      upstream_dist_path: "test/test19"
  test20:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test20"
      repo_name: "prototype-test/dist-repo-use-branch_test20"
      upstream_dist_path: "test/test20"
  test21:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test21"
      repo_name: "prototype-test/dist-repo-use-branch_test21"
      upstream_dist_path: "test/test21"
  test22:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test22"
      repo_name: "prototype-test/dist-repo-use-branch_test22"
      upstream_dist_path: "test/test22"