name: test all

# 这里通过手动触发器触发，也可以自定义其他触发方式
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test"
      repo_name: "prototype-test/dist-repo-use-branch_test"
      upstream_dist_path: "test"
  test2:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test2"
      repo_name: "prototype-test/dist-repo-use-branch_test2"
      upstream_dist_path: "test2"
  test3:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test3"
      repo_name: "prototype-test/dist-repo-use-branch_test3"
      upstream_dist_path: "test3"
  test4:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test4"
      repo_name: "prototype-test/dist-repo-use-branch_test4"
      upstream_dist_path: "test4"
  test5:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test5"
      repo_name: "prototype-test/dist-repo-use-branch_test5"
      upstream_dist_path: "test5"
  test6:
    uses: ./.github/workflows/validation-proxy.yml
    needs: []
    secrets: inherit
    with:
      name: "test6"
      repo_name: "prototype-test/dist-repo-use-branch_test6"
      upstream_dist_path: "test6"