name: validation-proxy

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
env:
  cd_branch_prefix: ${{ github.ref }}_-_cd_-_
  dist_branch_prefix: ${{ github.ref }}_-_dist_-_
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      # ::set-output 命令将被弃用，而 env 又不能直接在下面非 steps 中使用，而 steps 又不支持 uses 使用 action yml 文件……因此这里转发使用 env
      cd_branch_prefix: ${{ env.cd_branch_prefix }}
      dist_branch_prefix: ${{ env.dist_branch_prefix }}
    steps:
      - id: nothing-step
        run: |
          echo "这一步是必要的，去掉会报错"
  build:
    needs: setup
    uses: ./.github/workflows/validation.yml
    secrets: inherit
    with:
      cd_path: "${{ inputs.name }}/ci"
      cd_branch: "${{ needs.setup.outputs.cd_branch_prefix }}${{ inputs.name }}"
      dist_path: "${{ inputs.name }}/src"
      dist_branch: "${{ needs.setup.outputs.dist_branch_prefix }}${{ inputs.name }}"