name: validation-proxy

# ::set-output 命令将被弃用，而 env 又不能直接非 steps 的 job 中使用，而 steps 又不支持 uses 使用 action yml 文件……
# 有两种办法：一是使用 job 的 outputs 转发 env ，例如 job 名为 setup 则转发到 needs.setup.outputs（还必须定义 job 的 steps 否则报错），二是直接使用 inputs

on:
  workflow_call:
    inputs:
      name:
        description: "目标名，必须指定"
        required: true
        type: string
      repo_name:
        description: "目标（下游）仓库，格式为 owner/repository ，必须指定"
        required: true
        type: string
      main_branch:
        description: "目标（下游）仓库主分支名"
        default: main
        type: string
      upstream_repository:  # 上游仓库
        description: "上游仓库， 格式为 owner/repository ，不指定则默认为当前仓库"
        default: prototype-validation/dist-repo-use-branch_upstream # ${{ github.repository }}
        type: string

jobs:
  build:
    uses: ./.github/workflows/validation.yml
    secrets: inherit
    with:
      repository: ${{ inputs.upstream_repository }}
      main_branch: ${{ inputs.main_branch }}
      cd_path: ${{ inputs.name }}/ci
      cd_branch: ${{ inputs.main_branch }}_-_cd_-_${{ inputs.name }}
      dist_path: ${{ inputs.name }}/src
      dist_branch: ${{ inputs.main_branch }}_-_dist_-_${{ inputs.name }}
  sync:
    uses: ./.github/workflows/sync.yml
    secrets: inherit
    needs: [build]
    with:
      target_sync_repo: ${{ inputs.repo_name }}
      target_sync_branch: ${{ inputs.main_branch }}
      upstream_sync_branch: ${{ inputs.main_branch }}_-_dist_-_${{ inputs.name }}
      upstream_sync_repo: ${{ inputs.upstream_repository }}